In [19]:
import torch
import torch.nn as nn
torch.manual_seed(17) # For reproductivity

sentences = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
print(sentences)
print(sentences.size())

tensor([[1, 2, 4, 5],
        [4, 3, 2, 9]])
torch.Size([2, 4])


In [20]:
embedding = nn.Embedding(10, 3)
print(embedding.weight)
print(embedding(sentences))
print(embedding(sentences).size())

Parameter containing:
tensor([[-1.0462,  1.2305,  1.8662],
        [-0.3435,  0.0675,  0.4481],
        [-0.5986,  0.2515,  0.2113],
        [ 0.1331,  0.2522,  0.3827],
        [ 0.2344,  1.1805, -0.1851],
        [-0.4297,  0.1519, -0.1700],
        [-0.0601, -0.6294, -1.3345],
        [ 1.2675,  0.0667,  1.7792],
        [ 0.7402,  1.1313, -2.5713],
        [ 1.4333,  1.1304, -1.0084]], requires_grad=True)
tensor([[[-0.3435,  0.0675,  0.4481],
         [-0.5986,  0.2515,  0.2113],
         [ 0.2344,  1.1805, -0.1851],
         [-0.4297,  0.1519, -0.1700]],

        [[ 0.2344,  1.1805, -0.1851],
         [ 0.1331,  0.2522,  0.3827],
         [-0.5986,  0.2515,  0.2113],
         [ 1.4333,  1.1304, -1.0084]]], grad_fn=<EmbeddingBackward0>)
torch.Size([2, 4, 3])


In [21]:
import torch
import torch.nn as nn
torch.manual_seed(17) # For reproductivity

sentences = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
embedding = nn.Embedding(9, 3)
embedding(sentences)

IndexError: index out of range in self